# -*- coding: utf-8 -*-
# premise, angle for each scene id (1-221), matching scenes_raw.json ordering
PREMISES = {
1: ("A newly-opened repair shop's chaotic first day, where the trainee has to serve customers, use tools he barely knows, and an impatient boss decides whether to hire him for real.",
    "He's so eager and \"aktiv\" that he tries to fix everything at once, short-circuiting the shop's coffee machine live during his own job interview."),
2: ("A tiny start-up's cramped office where the boss proudly frames his diploma while explaining the embarrassingly low salary to a hopeful intern.",
    "The \"office\" turns out to be a repurposed storage room, and the entire \"Personal\" (staff) is one overworked employee wearing three hats."),
3: ("A disastrous job interview panel where an architect, a lawyer and an author all show up for the same single desk job by scheduling mix-up.",
    "Each candidate waves a different impressive certificate while the interviewer realizes there's only one project and one desk to share."),
4: ("An overstaffed org-chart farce: a company chief, a director, an on-call doctor and a grumpy civil servant all claim to run the same tiny department.",
    "Nobody can find the substitute when the real boss calls in sick, so four self-proclaimed leaders argue over one swivel chair."),
5: ("A small-town career fair where a butcher, an engineer, a photographer and a journalist set up booths, competing loudly for the same three visiting students.",
    "At exactly quitting time they strike a ridiculous compromise: whoever hands out the best free sausage sample \"wins\" the students."),
6: ("A talent-show-style hiring day where an artist, a mechanic and a musician each perform live to win an apprenticeship instead of handing in a CV.",
    "The workshop master judges the pay offer by how loud the applause is, so a guitar solo nearly wins the mechanic's job by mistake."),
7: ("A courtroom-sketch spoof of office life, where a judge, a professor, a reporter and an actor are all mistakenly summoned for the same secretarial vacancy.",
    "The intern is the only one who actually reads the job plan properly, while everyone else improvises dramatic excuses for being late."),
8: ("A frazzled entrepreneur juggles five overlapping appointments, including a singer and a coach both fighting for the same 3pm slot in his calendar.",
    "Out of sheer stress he signs a contract with the wrong visitor entirely, accidentally hiring an opera singer as his new sales rep."),
9: ("A scientist wanders into the wrong department's staff meeting, where instruction manuals pile ever higher on a table nobody understands.",
    "The \"consultation\" collapses into everyone reading an appliance manual aloud like a scientific paper, since nobody can find the real agenda."),
10: ("A factory's grand opening turns chaotic when the union shows up on day one demanding a raise before a single machine has started.",
     "The application deadline was yesterday, so a panicked worker sprints in mid-ceremony still clutching half-finished paperwork."),
11: ("A trade-fair booth squeezed between two rival companies, secretly grading each other's sales pitches like a school exam.",
     "One rep tries to resign dramatically mid-pitch just to steal the competitor's spotlight, then instantly regrets it."),
12: ("A job-placement office where a bewildered part-time applicant's paperwork keeps landing on the wrong desk for the wrong exam.",
     "The exact position she's qualified for keeps vanishing into administrative limbo as a filing cabinet topples onto the sign-up sheet."),
13: ("A networking mixer where guests urgently trade business cards while the host suddenly announces overtime is now \"required\" for everyone.",
     "A newly-hired employee gets fired and rehired three times in one evening as the tipsy boss keeps changing his mind between canapés."),
14: ("A retiring factory owner tries to train his flexible young replacement in a single half-day, guaranteeing unconvincingly that everything will go fine.",
     "The moment he retires mid-sentence and walks out, the replacement realizes he was never actually shown how the main machine works."),
15: ("A retirement party where the guest of honor keeps trying to quit again out of habit, while his replacement frantically drafts a five-year plan overnight.",
     "Every time someone toasts \"to your retirement,\" the old boss reflexively starts bossing people around again out of pure muscle memory."),
16: ("A group job-application workshop where five friends coach each other on sounding \"responsible and reliable\" in overacted mock interviews.",
     "Their practice spirals into an absurd bidding war over who deserves the imaginary job most, complete with a fake handshake contract."),

17: ("A frantic Saturday at the mall: a shopper withdraws cash from an ATM only to blow it all trying on an absurdly comfortable coat.",
     "He tries the coat on over his own coat, gets stuck taking it off in the fitting room, and has to be freed by staff."),
18: ("A colorful little shop's closing-down sale, where a customer haggles loudly over a cheap but \"chic\" shirt meant as a birthday gift.",
     "He insists on paying in cash from an overstuffed wallet, dramatically counting coins while the whole queue groans."),
19: ("A costume-shop window display goes wrong when a mannequin in an \"original\" designer suit gets mistaken for a customer trying on perfume.",
     "A vending machine outside jams and starts spitting out free samples, causing a mini stampede for the \"special offer.\""),
20: ("A flea-market stall run by an off-duty hairdresser who insists on styling customers' hair between selling secondhand hats from a catalog.",
     "He loses count of the total and keeps recalculating the receipt aloud while a nearby ATM queue grows impatient."),
21: ("A tiny shop owner haggles the price of a coat up and down with the same customer three times, each time \"discovering\" a new discount.",
     "By the end the sweater practically costs more in negotiation time than money, and the buyer leaves with a sack of unrelated bargains too."),
22: ("A supermarket clerk deals with a customer trying to return a single sock, insisting the whole pair is \"damaged\" on principle.",
     "The loudspeaker keeps announcing a jewelry \"special action\" upstairs, pulling half the queue away mid-argument."),
23: ("A bank teller patiently helps an elderly customer deposit money while he insists on triple-checking his sort code from three different cards.",
     "He hands over his bookstore card, his drugstore card, and finally the right bank card, in exactly the wrong order."),
24: ("A clothing-store checkout meltdown when a student discount card gets rejected and a whole outfit nearly gets put back.",
     "The cashier waives the fee purely because the student's dramatic sighing is scaring off other customers."),
25: ("A furious customer waves an overdue payment reminder, insisting the delivered brand-name folder was defective and demanding a refund.",
     "He empties a whole jar of loose coins onto the counter to \"prove\" he already paid, delaying the entire line."),
26: ("A uniformed insurance salesman corners weekend shoppers outside the mall, trying to bundle a policy into every purchase.",
     "He insists a grocery bag \"legally requires\" travel insurance, baffling an elderly shopper who just wanted to pay by card and leave."),
27: ("An overly elegant boutique clerk insists on gift-wrapping every item for free, explaining the \"financing plan\" makes it practically gratis.",
     "The wrapping takes so absurdly long that the price seems to rise from waiting alone."),
28: ("A popular pop-up shop lets customers try outfits before buying, so a shopper changes clothes behind a curtain five times to save money.",
     "He keeps re-emerging in increasingly mismatched, modern outfits, each time insisting THIS one is finally the affordable original."),
29: ("Two thrifty neighbors run an impromptu swap-market on the street, trading worn clothes instead of spending a cent.",
     "They get so competitive about frugality that they insist on \"insuring\" a threadbare old jacket before agreeing to trade it."),

30: ("A chaotic hotel breakfast buffet where guests toast with beer at 8am while a baker frantically bakes more rolls to keep up.",
     "Someone insists on letting their tea \"steep properly\" for twenty minutes, holding up the whole buffet line behind the toaster."),
31: ("A tiny countryside inn serves an enormous, mismatched breakfast: eggs, minced-meat patties, ice cream and pastries all on one groaning table.",
     "The innkeeper insists ice cream is a perfectly normal breakfast garnish, pouring it straight into a guest's glass of juice."),
32: ("A picnic in the park goes sideways when someone brings raw minced meat and a whole roast chicken instead of the agreed muesli-and-fruit spread.",
     "They end up needing a proper kitchen knife to cut the chicken on a blanket, to the horror of nearby joggers."),
33: ("A fussy Swiss-Austrian family argues over regional dialect words for chicken, beef and carrots while ordering a giant schnitzel.",
     "Nobody can agree what to call the afternoon snack, so the waiter just brings four different plates to be safe."),
34: ("A backyard barbecue where a suddenly ravenous, thirsty guest devours an entire roast alone before anyone else gets a bite.",
     "He apologizes by drizzling honey on everything left, including, accidentally, the vinegar bottle."),
35: ("A dramatic cooking-show parody where a chef insists a simple rice salad needs cream, pepper, mushrooms, tomatoes AND a giant dumpling.",
     "The waiter keeps sneaking spoonfuls of cake from the fridge between takes, getting caught on camera every single time."),
36: ("A train dining-car steward juggles a teapot, a wine order and a plate of ham while the innkeeper radios ahead demanding more sugar.",
     "A banana and a pear roll off the tray with every jolt of the train, and he catches them mid-air like a circus act."),
37: ("A confused new cafeteria worker can't tell canned beans from canned fruit and mixes up a batch meant for the staff's afternoon snack.",
     "She serves it anyway with a butter-coated fork, calling it \"an experimental new dish\" to a bewildered line of coworkers."),
38: ("A university cafeteria's mystery-meal day, where the \"surprise dessert\" turns out to be mashed potatoes with jam and margarine stirred in.",
     "A brave student tries it anyway, loudly rating it \"a bold new food group\" between grimaces."),
39: ("A chaotic home-cooking contest where two roommates fight over one pan, trying to make pizza, fries and a chocolate-plum sauce dessert at once.",
     "The portion sizes spiral out of control until the \"sauce\" experiment ends up covering the entire kitchen counter."),
40: ("A waiter recites an impossibly long, fresh-ingredient menu from memory to an increasingly thirsty, impatient couple who just want soup.",
     "By the time he finishes describing the tomato-onion soup, they've already ordered dessert twice out of pure hunger."),
41: ("A camping trip where two friends argue over whether the fruit is ripe enough to eat raw, then overcompensate by grilling absolutely everything.",
     "They end up hopelessly full and half-convinced they've invented a delicious new dish that is really just charred, oversalted chaos."),
42: ("A vegetarian cooking class asks a nervous beginner to prepare a spicy-sweet dish and he nearly cuts his finger slicing chili.",
     "He overcompensates for the scare by making it so spicy that everyone needs an emergency glass of water afterward."),

43: ("A Sunday visit to a retirement home where a nervous son-in-law finally meets his fiancée's parents while also babysitting her little brother.",
     "He keeps calling the elderly couple by the wrong names, then has to chase the kid through the entire care-home hallway."),
44: ("An awkward family reunion where a little girl demands more pocket money from every relative individually before saying goodbye.",
     "By the time she's hit up her brother, cousin and grandpa, she negotiates one final \"farewell bonus\" from a family friend too."),
45: ("A surprise birthday party mix-up: the wrong \"Mr. Müller\" neighbor shows up because two families share the exact same surname.",
     "The confused uncle spends half the party thinking his nephew has aged twenty years — it's actually the neighbor's teenage son."),
46: ("A retired grandpa insists on meeting his whole extended family at one tiny café table, listing everyone's marital status like a formal registry.",
     "The caretaker nurse who came to fetch him gets mistaken for yet another long-lost relative and sits through the whole roll call."),
47: ("A wedding invitation causes a ripple of confusion through an entire extended family, as everyone debates who was actually invited.",
     "The groom's own siblings end up needing help finding their invitation, having accidentally thrown it out with the junk mail."),
48: ("Three generations of women sort through childhood boxes, arguing lovingly over who really owned the ancient family doll.",
     "Grandma keeps \"proving\" ownership with increasingly implausible childhood stories nobody can verify, delighting the room."),
49: ("A daughter nervously invites her recently-divorced parents to the same dinner, hoping they'll be civil for one evening.",
     "They end up being suspiciously overly friendly to each other, which somehow worries her more than an actual argument would."),
50: ("A speed-dating night where a shy man keeps accidentally revealing painfully private details about his last relationship to every match.",
     "By match number five, everyone at the table already knows exactly why his last marriage ended, before he's even introduced himself."),
51: ("A chaotic goodbye scene at a train station: a couple can't decide whether they're breaking up or hopelessly in love, hugging and arguing at once.",
     "A distant relative on the platform loudly narrates the whole scene to strangers like it's a soap opera finale."),

52: ("An amateur theater troupe's chaotic opening night, filming their own show on a phone that keeps dying mid-scene while a golf-themed prop wobbles.",
     "The lead actor insists on printing his lines backstage last-minute because he never actually memorized them."),
53: ("A talent-show festival at the community pool where contestants perform ballet, poetry and piano on a stage built suspiciously near the water.",
     "One contestant's karaoke backup file is on a broken drive, forcing him to recite his poem entirely a cappella."),
54: ("A museum's after-hours members-only quiz night, where the orchestra accidentally starts playing a fairy-tale theme mid-question.",
     "The audience gets so absorbed solving riddles that nobody notices the museum wifi has quietly died, taking the quiz app with it."),
55: ("A kids' sports-day chaos at the local pool, where a tennis match, a theater rehearsal and impromptu training all collide in one stadium.",
     "A talent scout filming on an ancient camera insists he's \"discovered\" a future goalkeeper — really just a toddler chasing a beach ball."),
56: ("A carnival-costume basketball tournament where the scoreboard screen keeps glitching, printing score sheets wrong under mounting pressure.",
     "The \"rival team\" turns out to be the same players who just changed costumes at halftime, thoroughly confusing the referee."),
57: ("A carnival-parade prank where a \"professional athlete\" turns out to be a comedian livestreaming the chase on a wobbly laptop.",
     "The office copier gets dragged into the parade by mistake and somehow sets a new record for \"strangest float.\""),
58: ("A village hall's amateur ski-club awards ceremony turns into a spontaneous dance party after a silly playground race gets a \"star\" winner.",
     "The actual sports champion loses gracefully to a seven-year-old who cheated shamelessly, and everyone agrees it was still the best fun of the year."),
59: ("A circus-themed talent contest where the \"loser\" gets the loudest laughs of the night by accidentally telling the funniest joke on stage.",
     "His microphone battery dies right at the punchline, so the audience has to lean in and guess the ending, making it funnier."),
60: ("A nightclub throws a carnival-and-photography party where guests jam on flute and guitar while someone hunts for the missing TV remote.",
     "The DJ's hard drive crashes mid-set, so the crowd improvises with live gymnastics and flute solos instead of music."),
61: ("A pub's amateur book-and-opera club argues loudly over whose turn it is to host, filming the debate for a homemade video series.",
     "Someone insists on playing an ancient cassette of an opera aria, which nobody can turn off once it's copied over the party playlist by mistake."),
62: ("A tech-themed hiking event where participants sketch scenery on tablets, arguing which drawing app has the best technology mid-trail.",
     "Someone's keyboard falls into a stream, and the group improvises the rest of the \"digital sketching\" event with sticks in the mud."),
63: ("A lazy Sunday turns into an accidental celebration when a friend \"wins\" a photo contest just by uploading a picture of himself watching TV.",
     "Nobody can get the printer to work to print the winning photo, so they just photograph the screen and upload that instead."),
64: ("An eccentric hobby-fair booth where one artist paints, another sews, a third collects stamps, and a fourth insists archery counts as \"musical.\"",
     "He accidentally deletes his entire painting collection right before judging, and has to recreate a masterpiece from memory in five minutes."),
65: ("An overly competitive swim-and-sing talent contest where contestants insist on typing up \"backup copies\" of their scores between every round.",
     "The judge saves the wrong file and announces a diving contestant as the singing champion, to everyone's confusion and delight."),
66: ("Two rival hikers place an increasingly absurd bet on who'll draw the better mountain-view sketch by the end of the trail.",
     "The hike ends in a dramatic tie, so the spectating dog gets appointed the tiebreaking judge."),

67: ("A shy student accidentally becomes wildly popular after showboating about a \"famous\" cousin who turns out not to exist.",
     "He gets so worked up defending the lie that classmates find his outrage more endearing than suspicious, and he's only more beloved for it."),
68: ("A homesick exchange student confesses to missing his mom's cooking, and his host family treats it like a miraculous life crisis.",
     "They overreact so dramatically with sympathy that he starts believing his own homesickness really is a rare medical wonder."),
69: ("A nervous marriage proposal at a fairground goes wrong when the ring box turns out empty, sparking panic before it's found in his other pocket.",
     "His whole rehearsed speech about courage collapses into stammering doubt, then explodes into over-the-top joy the moment the ring reappears."),
70: ("A long, boring family car trip where a bored child's mood swings from tears to giggles to sudden hope every five minutes over nothing.",
     "The parents' patience finally snaps not from the crying, but from the child's insistence that the road itself is \"in a bad mood\" today."),
71: ("A surprise party planned with elaborate secrecy backfires when the guest of honor is so lazily relaxed he barely reacts to the \"shock.\"",
     "The disappointed party planners end up more startled by his calm than he ever was by the surprise itself."),
72: ("An overly diligent office worker throws himself a cozy little award ceremony after being secretly \"honored\" by nobody but himself.",
     "His cheeky coworkers play along so convincingly that he never realizes it was all one big inside joke at his expense."),
73: ("A first date at a fancy restaurant where both people are secretly, politely pretending to enjoy food they actually can't stand.",
     "Their overly polite compliments escalate until they both accidentally admit, at the exact same moment, that they hate seafood."),
74: ("A stand-up comedy open-mic night where a painfully nervous first-timer accidentally becomes the funniest act just by being visibly terrified.",
     "The more he apologizes for being boring, the harder the crowd laughs, until he bravely leans into the chaos."),
75: ("A nosy neighbor asks increasingly personal questions at a quiet garden party, until the normally calm host finally snaps and yells across the fence.",
     "The whole street peeks out their windows at the sudden shouting match, secretly delighted by the drama."),
76: ("A group of friends rushing to catch a train loudly second-guess every decision, complaining the whole way they'll surely miss it.",
     "They amuse themselves so much mocking their own panic that they nearly miss the train for real, laughing the entire sprint down the platform."),
77: ("A proud father refuses to admit he's lost at a board game, insisting loudly that losing on purpose was \"part of a secret strategy\" all along.",
     "His kids exchange amused, tolerant glances, quietly letting him keep his dignity while barely holding back laughter."),
78: ("A dog owner tearfully describes a wild dream where his loyal dog talked back to him, insisting it felt unbelievably real.",
     "His friends gently point out he's confusing the dream with the time he mixed up his dog's bark with his own snoring."),
79: ("A birthday party where the guest of honor dramatically exaggerates every gift's importance, swinging from moved to furious over the wrapping paper.",
     "His wild mood swings turn the party into a rollercoaster nobody signed up for, but everyone secretly enjoys the show."),

80: ("A school's model-UN club holds a chaotic mock vote on a trade conflict between two made-up countries, with students overacting foreign candidates.",
     "The \"peace treaty\" they finally agree on is really just an argument about swapping snacks between the import and export desks."),
81: ("A community theater's history pageant reenacts a royal war and refugee escape, with a grandpa proudly playing \"the king\" despite forgetting his lines.",
     "A protest scene meant to be serious dissolves into the cast striking over who gets to wear the one good crown prop."),
82: ("A school project on \"our capital city's culture\" spirals into a comically overblown documentary about the whole neighborhood's chaotic history.",
     "The students declare a minor downtown traffic jam a full-blown \"catastrophe\" worthy of the evening news."),
83: ("A town-hall meeting to \"reform\" the annual street festival turns into a passionate debate about tradition, survey clipboard in hand.",
     "The final vote is decided not by policy but by who brought the better homemade cake to the meeting."),
84: ("An international food festival meant to celebrate cultural diversity turns into a good-natured cooking \"battle\" between neighboring stalls.",
     "A volunteer historian gives an overly long speech about ancient traditions while everyone quietly sneaks off to eat before it gets cold."),
85: ("A local farmers' market \"goes on strike\" for a day in mock protest of a new regional regulation, while quietly still trading vegetables under the table.",
     "Their protest signs get comically flattened by a gust of wind, so they just vote to end the strike and go back to selling produce."),

86: ("A garage-sale haggling scene where a stubborn buyer insists on keeping \"all this stuff\" for a laughably low price, listing every random object as essential.",
     "The seller finally just gives him the whole box of junk for free purely to stop the ridiculous back-and-forth."),
87: ("A bureaucratic office worker explains, in increasingly circular language, why \"this matter\" is technically both allowed and not allowed at once.",
     "The confused customer eventually just shrugs and says it's fine either way, ending the standoff out of sheer exhaustion."),
88: ("Two roommates debate for ages about who should \"eventually\" go get some vague, unspecified something from the store.",
     "Neither wants to admit they don't actually know what they need, so they agree \"someone, someday\" will handle it."),
89: ("A group project meeting where \"someone\" was supposed to bring the materials, but nobody can figure out who, so everyone shrugs and improvises.",
     "The whole plan somehow works out anyway, purely through chaotic teamwork nobody can explain afterward."),
90: ("A painfully polite couple argue about restaurant choices entirely through indirect suggestions, neither willing to say what they actually want.",
     "They end up ordering nothing at all, insisting to the confused waiter that they're \"obviously\" both fine with whatever, naturally."),
91: ("A lost tourist insists he can \"obviously\" find his own way without a map, confidently declaring every wrong turn part of the plan.",
     "He ends up stuck in the exact same spot three times, each time insisting it was intentional all along."),
92: ("A frantic scavenger hunt where teammates search everywhere, demanding to know from each other, again and again, what they're even looking for.",
     "It turns out they've genuinely forgotten the rules entirely and have just been running around demanding answers from each other for no reason."),
93: ("A confused game-show contestant fires off every question word in existence trying to guess a mystery object, utterly stumping the host.",
     "He never actually guesses the answer but wins anyway for \"most impressively confused\" performance, at the very least."),

94: ("A hungover friend stumbles out of bed looking pale and can barely move, insisting he's just \"resting his eyes\" between violent yawns.",
     "He bumps into every piece of furniture in the apartment, blaming the furniture for \"moving itself\" overnight."),
95: ("A dramatic amateur first-aid class where a blond volunteer overreacts wildly to a tiny paper cut, insisting his whole leg feels feverish.",
     "The instructor gently explains that a scratched finger does not, in fact, require a full-body examination."),
96: ("A hypochondriac patient shows up at the hospital demanding every remedy in the pharmacy for a slightly sore knee, waving a suspiciously long list.",
     "The doctor eventually just hands him a single band-aid and a tissue, and he leaves triumphantly convinced it's a miracle cure."),
97: ("A nervous new doctor examines his first-ever patient, an old man with a magnificent beard, who coughs dramatically at every question.",
     "The doctor gets so distracted staring at the impressive beard that he forgets to actually check anything else."),
98: ("An ambulance is called for a \"seriously ill\" patient who turns out to have simply pulled a back muscle showing off at the gym.",
     "The paramedic can barely keep a straight face as the patient insists on being carried out dramatically anyway, for the full effect."),
99: ("A pharmacy queue full of sniffling, dramatic patients each insist their common cold is a rare, deadly virus requiring urgent attention.",
     "The unfazed pharmacist hands out the exact same tissue-and-tea remedy to everyone, wishing each a theatrically solemn \"get well soon.\""),
100: ("A wellness-retreat brochure promises miraculous skin cream and diet advice, but the \"clinic\" turns out to be a tiny tent with one guru.",
      "He insists his \"secret\" cream cures everything from flu to bad posture, applying it liberally to anyone who walks by."),
101: ("A dramatic ER waiting room where every patient insists their case is most urgent, from a sniffly nose to a supposedly life-threatening itchy shoulder.",
      "The exhausted nurse finally triages purely by whoever tells the funniest exaggerated story of their symptoms."),
102: ("A terrified patient at a routine checkup nearly faints at the mere sight of a syringe, despite it being just a normal vitamin shot.",
      "The nurse has to distract him with an elaborate story about toothpaste flavors just to get the injection done."),
103: ("An exhausted hiker collapses dramatically after a long trail, insisting he's caught a cold, frozen solid, and starving all at once on a mild afternoon.",
      "His friend hands him a sandwich and a blanket purely to make him stop narrating his own suffering out loud."),
104: ("A gym class where a scrawny beginner insists on lifting the heaviest weights to impress a crush, immediately coughing and collapsing from exhaustion.",
      "The crush is more charmed by his dramatic collapse than she would have been by actually lifting the weight."),
105: ("A nervous groom gets a last-minute shave and makeover before his wedding, sweating and running late while insisting he \"smells fine.\"",
      "The barber has to physically restrain him from bolting out mid-shave when he hears the ceremony music start early."),
106: ("A dramatic amateur theater death scene where the \"dying\" actor keeps recovering just long enough to fix his hair before collapsing again for effect.",
      "He insists on falling three separate times because the first two \"just didn't look strong enough.\""),
107: ("A slapstick cooking mishap leaves a chef with a minor burn, insisting on a full medical exam while his coworkers just want him to keep stirring.",
      "The visiting health inspector ends up \"prescribing\" him a hug and a band-aid, since that's clearly all he actually needs."),

108: ("An office worker keeps announcing \"Achtung! Important update!\" over the intercom about increasingly trivial things, like the coffee subscription.",
      "By the fifth announcement, everyone accepts whatever he says without listening, so nobody notices he cancelled the wrong meeting."),
109: ("A radio call-in show host demands callers \"answer honestly,\" but every caller dodges the question with a wildly exaggerated, unrelated story.",
      "The host finally just reports the funniest non-answer as \"breaking news\" purely for entertainment."),
110: ("An overly polite customer service call spirals into an absurd loop of \"please\" and \"thank you\" over cancelling a magazine subscription.",
      "He thanks the confused clerk so many times that she genuinely believes he loves the subscription and re-signs him up by accident."),
111: ("A bumbling local reporter conducts a street interview about a mysterious unmarked package, his phone ringing constantly mid-question.",
      "The package's \"anonymous sender\" turns out to be the reporter's own forgetful colleague, mailing himself a reminder note."),
112: ("An overwhelmed mail carrier delivers a mountain of congratulation letters to the wrong address, so a stranger gets fifty cards meant for someone else.",
      "He politely accepts them all and starts writing gracious thank-you replies to people he's never met."),
113: ("A radio call-in advice show erupts into an on-air argument when two listeners give the exact opposite tip for the same problem.",
      "The host has to hang up the receiver dramatically just to end the standoff before it derails the whole broadcast."),
114: ("A confused tourist reads a classified ad's address aloud in the worst possible pronunciation, baffling locals at the train station.",
      "Someone finally answers in equally broken pronunciation just to make him feel better, and neither realizes they've both been faking it."),
115: ("An airport announcement system garbles an important message so badly that passengers start a heated debate guessing what it said.",
      "The \"recommended\" gate turns out to be entirely made up by a bored passenger who just wanted to see if anyone would follow him."),
116: ("A small-town newspaper reporter chases a \"breaking news\" tip that turns out to be a neighbor's exaggerated voicemail about a missing garden gnome.",
      "He writes it up as front-page news, and the whole gullible town shows up demanding updates on the gnome investigation."),
117: ("A nervous intern gives his first big presentation, but his voice keeps cracking every time the projector shows an old ad instead of his slides.",
      "The audience assumes the ad is part of an elaborate joke and applauds, so he just rolls with it for the rest of the talk."),
118: ("Two strangers awkwardly debate whether to use formal or informal address the entire length of a train ride, never actually agreeing.",
      "By the final stop they're best friends, still politely arguing about grammar instead of exchanging names."),
119: ("A voicemail greeting gets re-recorded so many increasingly dramatic times that the final version sounds like a movie trailer, not a \"hello.\"",
      "Everyone who calls just leaves a message praising the greeting itself instead of the actual reason they called."),
120: ("A game of telephone at a party turns a simple message into complete nonsense, with each person confidently guessing wildly wrong.",
      "The last person in line just stays silent, too embarrassed to admit she genuinely has no idea what she's supposed to whisper."),
121: ("Two overly formal business partners argue on the phone about a contract detail, constantly interrupting each other while staying icily polite.",
      "They finally agree just to end the call and settle it in person, both secretly relieved to stop being so formal."),
122: ("A door-to-door salesman tries every persuasion trick in the book to get a skeptical homeowner to agree to a magazine subscription.",
      "The homeowner finally \"agrees\" purely to make him stop talking, then immediately regrets it while waving him off the porch."),

123: ("A courtroom-style classroom debate where students argue whether the class trip should happen, qualifying every point with \"however.\"",
      "They talk in such elaborate circles that the teacher has to remind them the actual decision was made an hour ago."),
124: ("Two roommates argue over doing the dishes, each giving increasingly elaborate, contradictory reasons why it's obviously the other's turn.",
      "Neither can actually remember the original reason they started arguing, so they just keep escalating out of sheer stubbornness."),
125: ("A school committee debates the exact conditions for an exception to the dress code, spiraling into an absurdly bureaucratic decision tree.",
      "The final \"consequence\" of their two-hour meeting is a rule so complicated nobody, including them, can actually follow it."),
126: ("A cooking show host insists a recipe works \"either this way or that,\" constantly adding contradictory extra ingredients to please viewers.",
      "The dish that finally emerges satisfies literally every possible request at once and looks completely inedible as a result."),
127: ("A tiny startup founder explains to investors that \"the more risk you take, the more it pays off,\" clarifying nothing while everyone nods along.",
      "Someone finally admits, mid-pitch, they still don't understand whether this startup belongs to a real industry at all."),
128: ("Two chess-obsessed friends argue endlessly about strategy, insisting the opposite move is correct purely to annoy each other.",
      "They eventually just swap seats and play each other's positions out of spite, somehow making the game better."),
129: ("A worried parent tries to prevent a toddler's tantrum by explaining, in absurdly formal logical terms, why \"because\" isn't reason enough.",
      "The toddler wins the argument anyway simply by crying louder than the explanation can be finished."),

130: ("A quirky detective-themed birthday party where the host insists on a \"special, extra-large, double portion\" of everything, from cake to costume.",
      "Every guest gets assigned an absurdly exaggerated \"case file\" nickname based on their favorite party snack."),
131: ("A robotics-club competition where a team's \"automatic\" invention almost works perfectly, calculating everything except the one crucial detail.",
      "The judges award it \"most impressively almost-excellent\" purely for its dramatic near-miss."),
132: ("A pie-sharing dispute among siblings turns into a geometry lesson as they argue over the exact fair size of each slice down to the crumb.",
      "They end up drawing circles and comparison charts on napkins just to settle who got the objectively bigger piece."),
133: ("A furniture-store customer insists on measuring absolutely every detail of a couch before committing, comparing width, height and shape endlessly.",
      "By the time he's satisfied, the store has closed for the night around him, tape measure still in hand."),
134: ("A statistics teacher tries to explain \"average versus reality\" using an oddly specific example about a square-shaped pizza slicing controversy.",
      "The class gets so distracted debating the pizza's shape that nobody actually learns the statistics lesson."),
135: ("A minimalist interior designer insists everything in the tiny apartment must be \"simple, uniform, and exactly one of each,\" maddening the clients.",
      "They secretly sneak in one extra colorful cushion just to see if he'll notice, and the ensuing meltdown is spectacular."),
136: ("A cooking-competition judge insists on tasting each dish an extremely precise number of times before dramatically declaring it \"fantastic or wrong.\"",
      "He's clearly just stalling for more free food, and contestants start suspiciously portioning identical backup plates."),
137: ("A group of friends try to split a giant pizza \"equally and simultaneously,\" resulting in a comically precise, high-stakes slicing negotiation.",
      "Someone insists half a slice is \"at most\" acceptable for a snack, sparking a debate about portion ethics."),
138: ("A tailor insists on a fully \"individual, ideal fit,\" taking so many complicated measurements the fitting barely finishes before closing time.",
      "The final suit is technically correct but comically too small, and he insists that's exactly the modern \"ideal\" style."),
139: ("A science-fair student proudly demonstrates an artificial rain machine, promising \"maximum output with minimal effort,\" which sputters weakly.",
      "After several increasingly desperate adjustments it finally floods the classroom instead, technically exceeding all expectations."),
140: ("A newlywed couple assembling flat-pack furniture insist the instructions \"normally\" make perfect sense, growing oddly positive despite the chaos.",
      "The shelf ends up wildly crooked, and they declare it \"practically perfect\" purely to avoid admitting defeat."),
141: ("A carpenter building a \"realistically simple\" round table ends up with a hilariously lopsided, oversized result after miscalculating every measurement.",
      "He insists a wonky table is \"relatively fine, actually,\" leaning it against the wall so nobody notices the tilt."),
142: ("An office betting pool tries to statistically guess the exact weight of a suspiciously heavy mystery package in the break room.",
      "The guesses range from absurdly light to comically heavy, and the \"special\" prize turns out to be the box itself."),
143: ("A group of hikers debate whether a steep hill is \"typically\" this exhausting, each guessing wildly different estimates of the remaining distance.",
      "They finally reach the top and discover it was a total anticlimax — a tiny, unremarkable bump, not the epic peak they imagined."),
144: ("An antiques appraiser on a TV show insists a family heirloom is \"probably, possibly\" quite valuable, torturing the owners with suspense.",
      "It turns out to be worth almost nothing, but he declares the story behind it \"priceless\" purely to soften the blow."),
145: ("A garden-club competition judges numerous nearly-identical prize roses, arguing over whose flowers are truly \"wonderfully\" superior.",
      "They eventually admit, almost as an afterthought, that they can't actually tell any of the roses apart at all."),

146: ("A confused delivery driver spins in circles following contradictory directions (\"up, down, in, out\") shouted from two opposite balconies.",
      "He finally just leaves the package exactly between both houses and lets the neighbors sort it out themselves."),
147: ("A lost driver stubbornly insists the destination is \"right there, nearby\" despite the GPS clearly showing it's still quite far away.",
      "He ends up parking triumphantly next to the wrong identical-looking corner store, three neighborhoods away."),
148: ("A confused tour guide gestures wildly in every direction at once, insisting the landmark is \"right there, over there, and also through here.\"",
      "The tour group wanders in a big, hopeless circle around the block before finding it was behind them the whole time."),
149: ("A game of hide-and-seek among adults at a party turns competitive, with hiders shouting contradictory clues to confuse the seeker.",
      "The seeker finally gives up and finds someone hiding in the most obvious spot the whole time, right behind the curtain."),
150: ("A furniture-rearranging argument between roommates escalates as they keep moving the same couch left, then middle, then right.",
      "They finally just leave it exactly where it started, exhausted, insisting it was \"obviously\" the best spot the whole time."),
151: ("A panicked cat owner searches the entire apartment for a missing pet, calling \"come out, come in, up here, over there\" with no luck.",
      "The cat, of course, was sitting calmly on top of the bookshelf the entire time, unbothered by the chaos."),
152: ("A group of tourists get comically lost trying to walk backward for a photo challenge, constantly turning around in a small park.",
      "They finally just sit down defeated on a visible bench, letting the photo challenge come to them instead."),
153: ("A magician's disappearing-act rehearsal goes wrong when his assistant actually vanishes behind the wrong curtain and gets stuck between two stage walls.",
      "The audience assumes it's part of the trick and applauds while the crew frantically searches everywhere backstage."),

154: ("A disorganized travel agency double-books a group tour, so half the tourists end up camping in a tent outside the \"fully booked\" hotel.",
      "They make the best of it, treating the tent as a quirky \"heritage experience\" and buying souvenir postcards of themselves camping."),
155: ("A guided castle tour gets sidetracked when the group insists on climbing every single tower for \"the view,\" ignoring the scheduled route.",
      "The exhausted guide gives up narrating history and just starts pointing out which tower has the best photo angle instead."),
156: ("A family's chaotic package-tour vacation involves a bus tour, a lost hotel reservation, and an impromptu night of camping when the desk can't find their booking.",
      "They return home insisting the accidental camping night was the actual highlight of the overpriced package deal."),

157: ("A nervous student caught copying a classmate's homework tries to convincingly \"analyze\" why the exact same wrong answer was purely a coincidence.",
      "The teacher lets him pass anyway, purely impressed by the elaborate, creative excuse he improvised on the spot."),
158: ("A stressed final-year student frantically flips through an entire encyclopedia the night before a big presentation, having forgotten the topic.",
      "He gives his talk on a completely random chapter, confidently bluffing his way through as if it were the assignment all along."),
159: ("A first-semester university student shows up to the wrong seminar entirely, too polite to leave, and ends up genuinely fascinated by an unrelated topic.",
      "He switches his whole degree goal on the spot, purely because he liked this professor's pencil-tapping teaching style."),
160: ("An intensive language course for beginners collapses into giggles as the teacher performs an exaggerated regional dialect dialogue nobody can imitate.",
      "A student's \"brilliant idea\" attempt at the dialect accidentally sounds like a completely different, hilarious made-up language."),
161: ("A pop quiz catches an unprepared student who tries to stall by asking, with mock philosophical seriousness, what the test's \"true purpose\" is.",
      "The teacher plays along just long enough that the whole class philosophizes past the entire period without answering a single question."),
162: ("A library research assignment turns chaotic when a translation app mistranslates a biology diagram's meaning into nonsense.",
      "The student presents the mistranslated version anyway, insisting it was an \"innovative reinterpretation\" of the original diagram."),
163: ("A group homework project spirals into a wildly imaginative history essay after nobody actually did the research and improvised from pure fantasy.",
      "Their teacher is so impressed by the creative confidence that she almost doesn't notice not a single fact is accurate."),
164: ("A tutoring session before a big graduation exam turns into a break-time debate about whether daydreaming counts as a legitimate study method.",
      "The tutor eventually admits her \"unconventional\" method is really just an excuse to extend the coffee break indefinitely."),
165: ("A university lecture hall erupts in confusion when the professor's chalkboard diagram accidentally looks exactly like a second-language pun.",
      "He has to completely rewrite his theory on the spot after realizing his own prep notes don't line up with the board."),
166: ("A young inventor proudly \"discovers\" a device that turns out to just be a familiar household object, wildly reinvented and unrecognizable.",
      "His teacher gently corrects him mid-oral-presentation, but he insists it's still technically a groundbreaking new invention."),
167: ("A strict professor insists on testing students purely on stylistic elegance, deducting points for \"insufficiently poetic\" written homework.",
      "A student who forgot to study entirely gets full marks purely for the theatrical flourish of his handwriting."),
168: ("A nervous student who missed the whole unit tries to summarize a book he's never read aloud, translating wildly from memory of the movie instead.",
      "His classmates are so entertained by the confidently wrong summary that they beg the teacher to let him \"present\" every week."),

169: ("A bewildered villager fills out an absurdly long municipal form just to officially register his own decades-old house in the town records.",
      "The clerk insists on stamping and confirming every single line twice, treating a routine visit like a major legal case."),
170: ("A lost-and-found office worker tries valiantly to reunite an eccentric elderly man with his lost hat, treating the case with courtroom-level seriousness.",
      "He dramatically reads out a mock \"verdict\" declaring the hat officially returned, complete with a gavel made from a rolled-up newspaper."),
171: ("A neighborhood watch meeting spirals into paranoid overreaction after someone mistakes a delivery driver for a suspicious thief.",
      "The meeting ends with everyone proudly showing off their ID cards to each other, just to be extra sure who's really a \"local resident.\""),
172: ("A false burglar-alarm mix-up sends a panicked resident sprinting to the emergency exit at 3am, only for the \"intruder\" to turn out to be a raccoon.",
      "The responding police officer writes up the world's most anticlimactic emergency report, barely holding back laughter."),
173: ("A mock trial school project accuses a hapless classmate purely on the flimsy coincidence of being seen near a missing lunch sandwich.",
      "The \"witness\" testimony collapses into giggles the moment the real culprit is caught red-handed still chewing."),
174: ("A construction-site inspector demands endless permits and confirmations before letting workers so much as touch a single brick of the new bridge.",
      "The fire department gets accidentally called in over a permit dispute, sirens blaring to a scene of pure bureaucratic paperwork."),
175: ("A ridiculously long queue forms outside the town registry office as everyone waits to sign a document nobody actually understands.",
      "A frustrated official finally announces the whole regulation was a clerical mistake, and the entire line groans in unison."),
176: ("A local news crew films a \"dangerous public menace\" story that turns out to be an old man illegally feeding pigeons in the town square.",
      "The reporter dramatically \"arrests\" him on camera with a rolled-up permit form just for comedic effect."),
177: ("A city council meeting debates whether jaywalking across an empty street at 3am is \"officially\" a punishable offense worth city resources.",
      "They vote unanimously to just let it go, secretly relieved to end a meeting that had somehow lasted three hours over nothing."),
178: ("A newly appointed mayor nervously signs his first official document banning something utterly trivial, like feeding ducks bread downtown.",
      "The whole town shows up in mock protest, \"accidentally\" bringing bread anyway, forcing him to publicly overturn his own rule within the hour."),

179: ("A school trip to a petting zoo and farm turns wonderfully chaotic when the \"wild\" animals prove far tamer than the overexcited children feeding them.",
      "A farmer patiently explains that no, the class cannot plant a rose bush in the middle of the sheep pasture, no matter how nicely they ask."),

180: ("A frantic commuter sprints to catch the S-Bahn, forgetting to buckle his bike helmet, only to watch the doors close the second he arrives.",
      "He ends up pedaling furiously alongside the tracks, absurdly racing the train to the next stop, and somehow nearly wins."),
181: ("An airport baggage mix-up sends a passenger's luggage onto the wrong plane, leaving him holding just a motorcycle helmet and a boat ticket.",
      "He decides to embrace the chaos and see where the mystery luggage's destination takes him instead of his own trip."),
182: ("A tourist juggling six different transport tickets tries to figure out the connecting bus, train and flight schedule from an outdated paper timetable.",
      "The friendly bus driver just laughs and personally walks him to the right platform, timetable be damned."),
183: ("A cyclist wobbling dangerously close to the sidewalk gets tangled with a passenger dragging an oversized suitcase at the main train station.",
      "A parked truck's flat tire adds to the chaos as the driver blocks half the platform fixing it just as everyone's train arrives."),
184: ("A flight attendant calmly announces a delayed takeoff due to \"traffic on the runway,\" as if planes could get stuck in a jam like cars at a red light.",
      "A passenger jokes that at this rate they'll get a parking ticket before they even leave the ground."),
185: ("A driving-school student accidentally turns onto a one-way street the wrong direction, panicking about the speed limit as a pedestrian zone looms.",
      "His instructor calmly notes it's technically also good ferry-boarding practice, since they're now heading straight for the harbor."),
186: ("A cable-car cabin breaks down mid-mountain right at a sharp curve, leaving passengers stranded with a spectacular, if terrifying, view.",
      "They pass the time debating whether this counts as an unscheduled \"station stop\" worth complaining about on the return trip."),
187: ("A confusing detour sign sends a tram, a subway train, and a line of cars into the same street simultaneously, each insisting they have the right of way.",
      "A mechanic from a nearby garage wanders out just to watch the standoff, refusing to help untangle it because it's \"too entertaining.\""),
188: ("A student pilot's first solo flight lesson goes comically wrong when he keeps confusing \"straight ahead\" with \"honk the horn,\" a habit from driving.",
      "His instructor has to talk him down slowly, reminding him planes, unlike cars, cannot simply be pushed into a parking spot."),
189: ("A road-trip couple's car sputters to a stop mid-journey, forcing them to wait at a tiny gas station arguing about who forgot to refuel.",
      "They finally get moving again just in time to watch their connecting bus overtake them and disappear down the highway."),

190: ("An eco-conscious farmer proudly demonstrates his new electric tractor in a field just as a dramatic thunderstorm rolls in over the mountains.",
      "Lightning flashes right as he's boasting about zero emissions, and everyone dives for cover, half-convinced the storm is personally offended."),
191: ("A weather-obsessed hiker insists on climbing a hill purely to feel closer to a distant thunderstorm rumbling over the valley below.",
      "His friends refuse to follow, watching from the riverbank as he gets comically drenched the moment he reaches the top."),
192: ("A beach camping trip goes sideways when a sudden storm rolls in, sending everyone scrambling for umbrellas while sand blows into every open bag.",
      "They end up huddled under one tiny umbrella, insisting they can still see the stars perfectly fine through the clouds."),
193: ("A local TV weather forecaster gives an overly dramatic report about a minor breeze, treating it like an epic battle between heat, cold and coastal wind.",
      "He gets so carried away describing the \"wild landscape\" that he forgets to mention tomorrow's forecast at all."),
194: ("A seaside environmental cleanup event turns competitive as volunteers race to collect the most litter before the incoming clouds threaten rain.",
      "Someone insists on checking the forecast every five minutes on his phone, which promptly dies from the humid sea air."),
195: ("A picnic planned for a \"mild, sunny\" day gets absurdly ambushed by hail, rain and fog in quick succession, all within the same hour outdoors.",
      "They stubbornly keep eating outside anyway, insisting the constantly changing weather is just \"adding variety\" to the meal."),
196: ("An eco-club project to grow vegetables gets ruined when a windy day scatters their compost everywhere, undoing weeks of careful \"green\" gardening.",
      "They declare the mess an accidental art installation about pollution, and it somehow wins a school prize."),

197: ("A weekend DIY renovation disaster sees a couple trying to fix the roof themselves, accidentally damaging a picture frame and flooding the bathroom.",
      "They give up, declare the chaos \"rustic charm,\" and just take a relaxing bath in the newly, unintentionally flooded bathroom."),
198: ("A ground-floor apartment viewing goes hilariously wrong when the agent trips over loose cables and knocks over \"genuine gold\" decorations that are clearly plastic.",
      "The prospective buyer is more charmed by the chaos than the actual house and puts in an offer on the spot."),
199: ("A furniture assembly nightmare leaves a couple staring at a mysterious leftover metal pipe and a suspicious hole in the wall where the shelf should be.",
      "They decide the hole is now \"intentional\" and hang a picture over it, calling it modern design."),
200: ("A building caretaker chases a trail of spilled laundry detergent up the stairwell, following it straight to a guilty tenant's overflowing trash bin.",
      "The tenant insists it's an avant-garde decorating choice — \"detergent-scented stairs\" — rather than admit he just tripped carrying laundry."),
201: ("A broken elevator forces the whole building to carry groceries, an old armchair and assorted household junk up the stairs, muddy footprints everywhere.",
      "Someone jokes that the ground floor now technically qualifies as a garden, given all the dirt tracked in."),
202: ("The building superintendent investigates a mysterious burning smell that turns out to be a forgotten dinner still on the stove three floors up.",
      "He ends up dragging the smoking oven tray down through the corridor himself, muttering about tenants who can't be trusted with a kitchen."),
203: ("A dusty attic clean-out reveals an old wardrobe, a cracked mirror, and a mysterious key that fits absolutely nothing in the house.",
      "The family spends the whole afternoon happily inventing wild theories about what secret the key must unlock."),
204: ("Moving day chaos sees a family's entire living room crammed onto the sidewalk while the landlord double-checks the new address on a scribbled note.",
      "The alarm clock, still ticking atop the pile, goes off right as the moving truck finally arrives, startling the whole street."),
205: ("A power outage forces a family to redecorate their whole living room by candlelight, arguing over furniture placement they can barely see.",
      "In the morning they discover the couch is now facing the garage instead of the fireplace, and decide to just leave it that way."),
206: ("A tenant frantically hides a mountain of unpacked moving boxes the moment the doorbell rings, pretending the flat is already perfectly tidy.",
      "The landlord isn't fooled for a second, having tripped over a stray box balanced precariously on the kitchen ladder."),
207: ("A power surge during a storm blows every outlet in the apartment at once, leaving a tenant fumbling with scissors and candle wax trying to fix things himself.",
      "He gives up and just moves the whole evening's activities out to the terrace, insisting it was always the plan."),
208: ("A new tenant moving into a dark, unfurnished apartment tries to set everything up in one chaotic evening, a stray toothbrush somehow in the toolbox.",
      "By the time he finally gets the lights on, he realizes he's been assembling furniture entirely in the wrong room the whole time."),
209: ("An overzealous plant-parent waters his houseplants so enthusiastically the floor turns comically slippery right as a delivery knocks at the door.",
      "He slides dramatically across the hallway to answer it, catching himself just before crashing into his own broken picture frame."),
210: ("A landlord proudly shows off a \"fully furnished, spotless\" rental apartment that turns out to be almost comically empty and mysteriously dusty already.",
      "The prospective tenant politely asks if the furniture is \"vertical, at least,\" gesturing at the one lonely chair leaning in the corner."),
211: ("A Sunday morning vacuuming spree wakes the entire building at dawn, prompting a grumpy neighbor to bang on the door demanding a more \"horizontal,\" reasonable schedule.",
      "They compromise by agreeing to only vacuum standing perfectly still and silent, which of course is impossible and hilarious to watch."),

212: ("A group of friends keep postponing the \"official start\" of a road trip, endlessly delaying with one more errand each, insisting they'll begin any minute.",
      "By the time they actually leave, it's already the time they were originally supposed to arrive."),
213: ("A wedding planner keeps constantly rescheduling the \"exact moment\" of the ceremony, dramatically announcing a new start time every few minutes.",
      "The groom eventually just starts the vows himself mid-chaos, insisting this particular moment feels official enough."),
214: ("An office worker's meticulously planned daily schedule collapses the moment he realizes today is actually a public holiday nobody told him about.",
      "He shows up to an empty building anyway, insisting on finishing his to-do list purely out of stubborn habit."),
215: ("A group rehearsing a school play insist \"this time, finally,\" they've got the ending right, after an absurd number of repeated run-throughs.",
      "The actual performance goes wrong in a brand new way anyway, proving rehearsal was apparently endless practice for nothing."),
216: ("A time-obsessed grandfather insists on fixing an exact, unmovable schedule for the family reunion, constantly comparing it unfavorably to \"how it was done\" decades ago.",
      "Nobody actually follows the schedule, and by evening he admits, in hindsight, the chaos was more fun than his old rigid version ever was."),
217: ("A forgetful uncle tells the exact same \"recent\" story at every family gathering, insisting each time it just happened, though everyone's heard it for years.",
      "The kids start a running tally, cheering loudly each time he reaches the punchline, to his utter confusion."),
218: ("A couple's ongoing debate about whose turn it is to cook keeps circling back \"once more\" every single night, meanwhile takeout quietly wins by default.",
      "They finally realize neither has actually cooked in weeks, having been meaning to \"starting next time\" for what turns out to be a month."),
219: ("A famously unpunctual friend suddenly, shockingly, shows up exactly on time to a party, causing everyone to panic that something must be wrong.",
      "It turns out he simply set fifteen alarms, a regularity so rare it's treated as a historic, immediate cause for celebration."),
220: ("A birthday party originally planned for the afternoon keeps getting postponed \"at the latest\" until it's suspiciously spent entirely being planned rather than happening.",
      "By the time they finally hold it, it's technically the day before the actual birthday, having somehow drifted backward in time through pure procrastination."),
221: ("A confused grandmother keeps asking what day it is mid-conversation, \"provisionally\" agreeing with whatever answer sounds most convincing.",
      "The family eventually just tells her it's always \"the day after tomorrow,\" which she finds oddly comforting and stops asking altogether."),
}
