# -*- coding: utf-8 -*-
manual_round3 = {
"Abgase":"WETTER","ab":"RAUM","abholen":"VERKEHR","abstimmen":"GESELLSCHAFT","anbieten":"EINKAUFEN",
"ansehen":"FREIZEIT","auffallen":"GEFUEHLE","auffordern":"KOMMUNIKATION","aufführen":"FREIZEIT",
"aufgeben":"ARBEIT","aufhalten":"ZEIT","aufhören":"ZEIT","auflösen":"SCHULE","aufmerksam":"SCHULE",
"aufnehmen":"FREIZEIT","aufpassen":"FAMILIE","aufschreiben":"SCHULE","auftreten":"FREIZEIT",
"ausfallen":"VERKEHR","ausgeben":"EINKAUFEN","ausgehen":"FREIZEIT","ausmachen":"WOHNEN",
"ausrichten":"KOMMUNIKATION","ausruhen":"KOERPER","ausschließen":"LOGIK","ausschließlich":"LOGIK",
"aussehen":"KOERPER","ausstellen":"FREIZEIT","aussuchen":"EINKAUFEN","auswählen":"EINKAUFEN",
"baden":"WOHNEN","basteln":"FREIZEIT","bauen":"WOHNEN","beachten":"STADT","beantworten":"KOMMUNIKATION",
"befreit":"EINKAUFEN","befriedigend":"SCHULE","begegnen":"FAMILIE","begleiten":"FAMILIE",
"begrüßen":"KOMMUNIKATION","behandeln":"KOERPER","beinahe":"MENGE","bekannt geben":"KOMMUNIKATION",
"beobachten":"SCHULE","beraten":"ARBEIT","beruhigen":"GEFUEHLE","beschließen":"GESELLSCHAFT",
"beschädigen":"WOHNEN","beschäftigen":"ARBEIT","besorgen":"EINKAUFEN","bestehen":"SCHULE",
"bestellen":"ESSEN","besuchen":"FAMILIE","bewegen":"KOERPER","beweisen":"STADT","bieten":"EINKAUFEN",
"bisher":"ZEIT","blond":"KOERPER","bloß":"GLUE","brechen":"KOERPER","danach":"ZEIT","dann":"ZEIT",
"das Abenteuer":"FREIZEIT","das Abitur":"SCHULE","das Abonnement":"KOMMUNIKATION","das Alter":"FAMILIE",
"das Blatt":"SCHULE","das Couvert":"KOMMUNIKATION","das Denkmal":"REISEN","das Dessert":"ESSEN",
"das Detail":"MENGE","das Dorf":"STADT","das Eck":"RAUM","das Einkommen":"ARBEIT","das Eis":"ESSEN",
"das Ergebnis":"SCHULE","das Feld":"WETTER","das Feuerzeug":"WOHNEN","das Forum":"KOMMUNIKATION",
"das Fundbüro":"STADT","das Gebiet":"WETTER","das Gebäude":"STADT","das Geheimnis":"GEFUEHLE",
"das Gericht":"STADT","das Gerät":"WOHNEN","das Geschirr":"WOHNEN","das Geschlecht":"FAMILIE",
"das Gewissen":"GEFUEHLE","das Gift":"KOERPER","das Heimweh":"GEFUEHLE","das Hendl":"ESSEN",
"das Hähnchen/Hühnchen":"ESSEN","das Kraftwerk":"WETTER","das Kreuz":"KOERPER","das Kuvert":"KOMMUNIKATION",
"das Lager":"ARBEIT","das Land":"GESELLSCHAFT","das Leben":"GEFUEHLE","das Lied":"FREIZEIT",
"das Mitglied":"FREIZEIT","das Mittel":"KOERPER","das Modell":"EINKAUFEN","das Nahrungsmittel":"ESSEN",
"das Obst":"ESSEN","das Opfer":"STADT","das Paar":"FAMILIE","das Parfüm":"EINKAUFEN","das Pech":"GEFUEHLE",
"das Plakat":"KOMMUNIKATION","das Poulet":"ESSEN","das Publikum":"FREIZEIT","das Quartier":"REISEN",
"das Risiko":"ARBEIT","das Rohr":"WOHNEN","das Schaufenster":"EINKAUFEN","das Schwammerl":"ESSEN",
"das Streichholz":"WOHNEN","das Studio":"FREIZEIT","das Stück/-stück":"MENGE","das Suchtmittel":"KOERPER",
"das Symbol":"KOMMUNIKATION","das Taschengeld":"FAMILIE","das Taschentuch":"KOERPER","das Teil":"MENGE",
"das Tempo":"VERKEHR","das Tuch":"WOHNEN","das Unglück":"GEFUEHLE","das Vergnügen":"GEFUEHLE",
"das Verhalten":"GEFUEHLE","das Verhältnis":"FAMILIE","das Vertrauen":"GEFUEHLE","das Viertel":"STADT",
"das Vitamin":"KOERPER","das Wasser":"ESSEN","das Werk":"ARBEIT","das Wunder":"GEFUEHLE",
"das Zündholz":"WOHNEN","das/der Obers":"ESSEN","das/der Zvieri/Znüni":"ESSEN","der Abschluss":"SCHULE",
"der Abschnitt":"SCHULE","der Alarm":"STADT","der Alkohol":"ESSEN","der Anschluss":"VERKEHR",
"der Appetit":"ESSEN","der Aufenthalt":"REISEN","der Ball":"FREIZEIT","der Bau":"WOHNEN",
"der Besuch":"FAMILIE","der Beweis":"STADT","der Blick":"KOERPER","der Bogen":"SCHULE","der Druck":"FREIZEIT",
"der Eindruck":"GEFUEHLE","der Einfall":"SCHULE","der Enkel":"FAMILIE","der Ersatz":"ARBEIT",
"der Fahrer":"VERKEHR","der Fasching":"FREIZEIT","der Fauteuil":"WOHNEN","der Fehler":"SCHULE",
"der Fleischhauer":"ARBEIT","der Gast":"ESSEN","der Gegenstand":"WOHNEN","der Gegner":"FREIZEIT",
"der Glückwunsch":"KOMMUNIKATION","der Gott":"GESELLSCHAFT","der Gruß":"KOMMUNIKATION","der Held":"FREIZEIT",
"der Herr":"KOMMUNIKATION","der Hörer":"KOMMUNIKATION","der Imbiss":"ESSEN","der Inhalt":"SCHULE",
"der Kanal":"FREIZEIT","der Karneval":"FREIZEIT","der Katalog":"EINKAUFEN","der Knopf":"EINKAUFEN",
"der Kontakt":"KOMMUNIKATION","der Korridor":"WOHNEN","der Kreis":"MENGE","der König":"GESELLSCHAFT",
"der Lautsprecher":"FREIZEIT","der Leser":"KOMMUNIKATION","der Lärm":"STADT","der Magen":"KOERPER",
"der Mann":"FAMILIE","der Mensch":"GESELLSCHAFT","der Metzger":"ARBEIT","der Nichtraucher":"KOERPER",
"der Ordner":"ARBEIT","der Passagier":"VERKEHR","der Patient":"KOERPER","der Pensionist":"FAMILIE",
"der Pilz":"ESSEN","der Platz":"STADT","der Punkt":"MENGE","der Pöstler":"KOMMUNIKATION","der Rahm":"ESSEN",
"der Raucher":"KOERPER","der Raum":"WOHNEN","der Rechner":"FREIZEIT","der Rentner":"FAMILIE",
"der Saal":"FREIZEIT","der Sack":"EINKAUFEN","der Satz":"SCHULE","der Schaden":"EINKAUFEN",
"der Schalter":"STADT","der Schirm":"WETTER","der Schluss":"ZEIT","der Schmutz":"WOHNEN",
"der Schreck":"GEFUEHLE","der Schritt":"KOERPER","der Sitz":"VERKEHR","der Spaß":"FREIZEIT",
"der Standpunkt":"KOMMUNIKATION","der Start":"VERKEHR","der Steward":"VERKEHR","der Stift":"SCHULE",
"der Stil":"EINKAUFEN","der Stress":"ARBEIT","der Sturm":"WETTER","der Teil":"MENGE",
"der Teilnehmer":"SCHULE","der Tipp":"KOMMUNIKATION","der Transport":"VERKEHR","der Traum":"GEFUEHLE",
"der Treffpunkt":"FAMILIE","der Turm":"REISEN","der Unfall":"VERKEHR","der Verlag":"ARBEIT",
"der Verlust":"ARBEIT","der Versuch":"SCHULE","der Virus":"KOERPER","der Vorort":"STADT",
"der Vorwurf":"KOMMUNIKATION","der Weg":"RAUM","der Wirt":"ESSEN","der Wohnort":"WOHNEN",
"der Wohnsitz":"WOHNEN","der Wunsch":"GEFUEHLE","der Zuhörer":"KOMMUNIKATION","der Zuschauer":"FREIZEIT",
"der Zuschlag":"VERKEHR","der Zweifel":"GEFUEHLE","der/das Obers":"ESSEN","die Abbildung":"SCHULE",
"die Absicht":"GEFUEHLE","die Abteilung":"ARBEIT","die Adresse":"KOMMUNIKATION","die Ahnung":"GEFUEHLE",
"die Aktion":"EINKAUFEN","die Aktivität":"FREIZEIT","die Alternative":"MENGE","die Angabe":"SCHULE",
"die Anlage":"EINKAUFEN","die Anrede":"KOMMUNIKATION","die Aufforderung":"KOMMUNIKATION",
"die Aufnahme":"FREIZEIT","die Ausgabe":"EINKAUFEN","die Ausnahme":"LOGIK","die Aussicht":"REISEN",
"die Ausstellung":"FREIZEIT","die Auswahl":"EINKAUFEN","die Baustelle":"STADT","die Beratung":"ARBEIT",
"die Beschäftigung":"ARBEIT","die Besserung":"KOERPER","die Bewegung":"KOERPER","die Biologie":"SCHULE",
"die Bohne":"ESSEN","die Brille":"KOERPER","die Brücke":"STADT","die Buchhandlung":"EINKAUFEN",
"die Burg":"REISEN","die Bäckerei":"ESSEN","die Büchse":"ESSEN","die Chance":"ARBEIT","die Creme":"KOERPER",
"die Dame":"KOMMUNIKATION","die Datei":"FREIZEIT","die Daten":"FREIZEIT","die Dose":"ESSEN",
"die Droge":"KOERPER","die Drogerie":"EINKAUFEN","die Dusche":"WOHNEN","die Ecke":"RAUM",
"die Einführung":"SCHULE","die Einladung":"FAMILIE","die Einnahme":"EINKAUFEN","die Einrichtung":"WOHNEN",
"die Einzelheit":"MENGE","die Eisenbahn":"VERKEHR","die Entscheidung":"LOGIK","die Erholung":"KOERPER",
"die Erhöhung":"ARBEIT","die Ermäßigung":"EINKAUFEN","die Ernte":"WETTER","die Eröffnung":"ARBEIT",
"die Farbe":"EINKAUFEN","die Fasnacht":"FREIZEIT","die Figur":"KOERPER","die Flasche":"ESSEN",
"die Flucht":"GESELLSCHAFT","die Flüssigkeit":"ESSEN","die Form":"MENGE","die Fortsetzung":"FREIZEIT",
"die Fotografie":"FREIZEIT","die Frau":"FAMILIE","die Freiheit":"GESELLSCHAFT","die Frist":"ARBEIT",
"die Führung":"REISEN","die Gebrauchsanweisung":"WOHNEN","die Geduld":"GEFUEHLE","die Gefahr":"STADT",
"die Gemeinschaft":"GESELLSCHAFT","die Geschichte":"SCHULE","die Gewohnheit":"GEFUEHLE",
"die Grafik":"FREIZEIT","die Gratulation":"KOMMUNIKATION","die Gruppe":"SCHULE","die Gymnastik":"FREIZEIT",
"die Hauptstadt":"GESELLSCHAFT","die Hilfe":"FAMILIE","die Hoffnung":"GEFUEHLE","die Infektion":"KOERPER",
"die Jause":"ESSEN","die Jeans":"EINKAUFEN","die Karte":"REISEN","die Kassette":"FREIZEIT",
"die Kirche":"REISEN","die Kiste":"WOHNEN","die Klingel":"WOHNEN","die Kommunikation":"KOMMUNIKATION",
"die Kunst":"FREIZEIT","die Lage":"RAUM","die Lebensmittel":"ESSEN","die Leiter":"WOHNEN",
"die Leute":"GESELLSCHAFT","die Lieferung":"EINKAUFEN","die Linie":"VERKEHR","die Liste":"SCHULE",
"die Lust":"GEFUEHLE","die Lüge":"KOMMUNIKATION","die Mahnung":"EINKAUFEN","die Maschine":"ARBEIT",
"die Matura":"SCHULE","die Mauer":"STADT","die Medien":"KOMMUNIKATION","die Messe":"ARBEIT",
"die Metropole":"GESELLSCHAFT","die Mobilität":"VERKEHR","die Mode":"EINKAUFEN","die Mühe":"ARBEIT",
"die Nachfrage":"GESELLSCHAFT","die Nachspeise":"ESSEN","die Notaufnahme":"KOERPER","die Pause":"SCHULE",
"die Person":"GESELLSCHAFT","die Pflicht":"ARBEIT","die Qualität":"EINKAUFEN","die Reaktion":"GEFUEHLE",
"die Reform":"GESELLSCHAFT","die Reihe":"RAUM","die Reihenfolge":"MENGE","die Rente":"FAMILIE",
"die Rezeption/Reception":"REISEN","die Richtung":"RAUM","die Rolle":"FREIZEIT","die Runde":"FREIZEIT",
"die Rückfahrt":"VERKEHR","die Rückkehr":"REISEN","die Rücksicht":"VERKEHR","die Sahne":"ESSEN",
"die Scheibe":"ESSEN","die Schlange":"STADT","die Schuld":"STADT","die Schwierigkeit":"ARBEIT",
"die Seite":"SCHULE","die Serie":"FREIZEIT","die Situation":"GEFUEHLE","die Spur":"VERKEHR",
"die Station":"VERKEHR","die Stelle":"ARBEIT","die Stimme":"KOMMUNIKATION","die Stimmung":"GEFUEHLE",
"die Strecke":"VERKEHR","die Stufe":"WOHNEN","die Stunde":"ZEIT","die Störung":"WOHNEN","die Sucht":"KOERPER",
"die Summe":"EINKAUFEN","die Szene":"FREIZEIT","die Tabelle":"SCHULE","die Tatsache":"LOGIK",
"die Teilnahme":"SCHULE","die Terrasse":"WOHNEN","die Therapie":"KOERPER","die Toilette":"WOHNEN",
"die Tropfen":"KOERPER","die Umfrage":"GESELLSCHAFT","die Unterhaltung":"FREIZEIT","die Unterlagen":"ARBEIT",
"die Unterstützung":"ARBEIT","die Veranstaltung":"FREIZEIT","die Verbindung":"VERKEHR",
"die Vermittlung":"ARBEIT","die Versammlung":"GESELLSCHAFT","die Visitenkarte":"ARBEIT",
"die Vorbereitung":"SCHULE","die Wahrheit":"KOMMUNIKATION","die Wand":"WOHNEN","die Welt":"GESELLSCHAFT",
"die Wissenschaft":"SCHULE","die Zange":"WOHNEN","die Zeile":"SCHULE","die Zigarette":"KOERPER",
"die Zone":"STADT","die Zusammenarbeit":"ARBEIT","die Zünder":"WOHNEN","die Änderung":"LOGIK",
"die/das Glace/Glacé":"ESSEN","direkt":"MENGE","drehen":"FREIZEIT","dringend":"ARBEIT","drücken":"WOHNEN",
"duschen":"WOHNEN","duzen":"KOMMUNIKATION","egal":"GLUE","eher":"MENGE","eigen-":"GLUE",
"ein bisschen":"MENGE","ein-":"GLUE","einfallen":"SCHULE","einfügen":"FREIZEIT","einführen":"ARBEIT",
"einladen":"FAMILIE","einnehmen":"KOERPER","einrichten":"WOHNEN","einschalten":"WOHNEN",
"einschließlich":"MENGE","einsetzen":"ARBEIT","eintragen":"STADT","einverstanden":"KOMMUNIKATION",
"entdecken":"SCHULE","entgegenkommen":"VERKEHR","entscheiden":"LOGIK","entschlossen":"GEFUEHLE",
"entsorgen":"WOHNEN","entspannend":"GEFUEHLE","entstehen":"LOGIK","erhöhen":"EINKAUFEN",
"erleichtern":"GEFUEHLE","erreichen":"VERKEHR","ersetzen":"ARBEIT","erstellen":"ARBEIT",
"erwarten":"GEFUEHLE","eröffnen":"ARBEIT","fallen":"KOERPER","farbig":"EINKAUFEN","fassen":"STADT",
"fast":"MENGE","faulenzen":"FREIZEIT","feststellen":"SCHULE","finden":"GEFUEHLE","flexibel":"ARBEIT",
"fliehen":"GESELLSCHAFT","fließen":"WETTER","fließend":"SCHULE","fortsetzen":"ZEIT","frei":"ARBEIT",
"freiwillig":"GESELLSCHAFT","fremd":"GESELLSCHAFT","fällig":"EINKAUFEN","gefallen":"GEFUEHLE",
"gefährlich":"STADT","geheim":"GEFUEHLE","gelingen":"ARBEIT","genießen":"FREIZEIT","gern/gerne":"GEFUEHLE",
"gewohnt":"GEFUEHLE","gewöhnen":"GEFUEHLE","gießen":"WOHNEN","giftig":"KOERPER","glauben":"GEFUEHLE",
"gratulieren":"KOMMUNIKATION","gründlich":"ARBEIT","grüßen":"KOMMUNIKATION","gucken":"FREIZEIT",
"haltbar":"ESSEN","halten":"VERKEHR","heimlich":"GEFUEHLE","heißen":"KOMMUNIKATION","helfen":"FAMILIE",
"herzlich":"KOMMUNIKATION","hinterher":"ZEIT","hinterlassen":"KOMMUNIKATION","hoffen":"GEFUEHLE",
"hoffentlich":"GEFUEHLE","hängen":"WOHNEN","illegal":"STADT","im Freien":"WETTER",
"in Pension gehen/sein":"ARBEIT","in Rente gehen/sein":"ARBEIT","inklusive":"EINKAUFEN",
"intensiv":"ARBEIT","jung":"FAMILIE","kaum":"MENGE","klagen":"STADT","klingeln":"WOHNEN",
"klingen":"KOMMUNIKATION","klopfen":"WOHNEN","klären":"LOGIK","korrigieren":"SCHULE","lange":"ZEIT",
"langsam":"VERKEHR","laut":"WOHNEN","leben":"FAMILIE","leid tun":"GEFUEHLE","leiden":"KOERPER",
"leider":"GEFUEHLE","leihen":"EINKAUFEN","leise":"WOHNEN","lernen":"SCHULE","liefern":"EINKAUFEN",
"locker":"GEFUEHLE","lustig":"GEFUEHLE","löschen":"FREIZEIT","lügen":"KOMMUNIKATION",
"meinetwegen":"GLUE","menschlich":"GESELLSCHAFT","mischen":"ESSEN","miss-":"GLUE",
"mobil/mobil-":"VERKEHR","musikalisch":"FREIZEIT","männlich":"FAMILIE","nachher":"ZEIT","nass":"WETTER",
"neu":"MENGE","nicht":"GLUE","niedrig":"MENGE","nur":"GLUE","nähen":"FREIZEIT","nämlich":"GLUE",
"offen":"WOHNEN","ohne":"GLUE","passiv":"GEFUEHLE","pauschal":"REISEN","pensioniert werden/sein":"ARBEIT",
"persönlich":"GEFUEHLE","plötzlich":"ZEIT","privat":"FAMILIE","pro":"MENGE","rauchen":"KOERPER",
"reagieren":"GEFUEHLE","realisieren":"ARBEIT","regional":"GESELLSCHAFT","rennen":"KOERPER",
"rufen":"KOMMUNIKATION","sammeln":"FREIZEIT","schaden":"KOERPER","schalten":"WOHNEN","schauen":"FREIZEIT",
"scheinen":"WETTER","schicken":"KOMMUNIKATION","schieben":"VERKEHR","schießen":"FREIZEIT",
"schimpfen":"GEFUEHLE","schlagen":"FREIZEIT","schließen":"WOHNEN","schnell":"VERKEHR","schuld":"STADT",
"schuldig":"STADT","schädlich":"KOERPER","schätzen":"MENGE","sich bedanken":"KOMMUNIKATION",
"sich beteiligen":"GESELLSCHAFT","sich einigen":"KOMMUNIKATION","sich entschließen":"GEFUEHLE",
"sich ereignen":"ZEIT","sich erholen":"KOERPER","sich erkundigen":"KOMMUNIKATION",
"sich etwas gefallen lassen":"GEFUEHLE","sich konzentrieren":"SCHULE","sich nähern":"RAUM",
"sich umziehen":"EINKAUFEN","sich verlaufen":"RAUM","sichern":"FREIZEIT","sichtbar":"RAUM",
"siezen":"KOMMUNIKATION","sinken":"MENGE","so viel/so viel wie":"MENGE","sogar":"GLUE",
"sogenannt-":"GLUE","soviel":"MENGE","springen":"KOERPER","spüren":"GEFUEHLE","stammen":"GESELLSCHAFT",
"starten":"VERKEHR","stehen bleiben":"VERKEHR","steigen":"MENGE","stilistisch":"SCHULE","stimmen":"LOGIK",
"stoppen":"VERKEHR","streng":"SCHULE","stören":"WOHNEN","stürzen":"KOERPER","suchen":"GLUE",
"süchtig":"KOERPER","tauschen":"EINKAUFEN","teilen":"FAMILIE","teilnehmen":"SCHULE","tippen":"FREIZEIT",
"transportieren":"VERKEHR","treffen":"FAMILIE","treiben":"FREIZEIT","treten":"KOERPER","träumen":"GEFUEHLE",
"umgehen":"LOGIK","umgekehrt":"LOGIK","un-":"GLUE","unentschieden":"FREIZEIT","ungewöhnlich":"GEFUEHLE",
"unterbrechen":"KOMMUNIKATION","unterhalten":"KOMMUNIKATION","unterlassen":"STADT","unterscheiden":"MENGE",
"unterstützen":"ARBEIT","unterwegs":"VERKEHR","ursprünglich":"ZEIT","verbessern":"SCHULE",
"verbinden":"KOMMUNIKATION","verbrauchen":"EINKAUFEN","verbrennen":"KOERPER","verbringen":"ZEIT",
"vergeblich":"GEFUEHLE","vergrößern":"MENGE","verhindern":"LOGIK","verlassen":"FAMILIE",
"verlängern":"ZEIT","vermeiden":"LOGIK","vermissen":"GEFUEHLE","verpassen":"VERKEHR",
"verpflegen":"ESSEN","verpflichtet":"ARBEIT","verraten":"KOMMUNIKATION","verschieben":"ZEIT",
"verschreiben":"KOERPER","verschwinden":"RAUM","versprechen":"KOMMUNIKATION","verstecken":"RAUM",
"versuchen":"SCHULE","versäumen":"SCHULE","verteilen":"ARBEIT","vertrauen":"GEFUEHLE",
"verwechseln":"GEFUEHLE","verzichten":"GEFUEHLE","verändern":"LOGIK","veröffentlichen":"KOMMUNIKATION",
"vor allem":"GLUE","voraussichtlich":"ZEIT","vorbereiten":"SCHULE","vorhaben":"ZEIT","vorher":"ZEIT",
"vorhin":"ZEIT","vorkommen":"LOGIK","wachsen":"WETTER","wann":"ZEIT","warten":"VERKEHR","waschen":"WOHNEN",
"wechseln":"EINKAUFEN","weiblich":"FAMILIE","weltweit":"GESELLSCHAFT","wenden":"VERKEHR",
"wenigstens":"MENGE","wetten":"FREIZEIT","wie viel":"MENGE","wild":"TIERE","winken":"KOMMUNIKATION",
"wohnen":"WOHNEN","wünschen":"GEFUEHLE","zeigen":"KOMMUNIKATION","zerstören":"GESELLSCHAFT",
"ziehen":"KOERPER","zu sein":"GLUE","zuhören":"KOMMUNIKATION","zumachen":"WOHNEN","zumindest":"GLUE",
"zurechtkommen":"ARBEIT","zusagen":"KOMMUNIKATION","zusammenfassen":"SCHULE","zuschauen":"FREIZEIT",
"zuverlässig":"ARBEIT","zweifeln":"GEFUEHLE","zwingen":"LOGIK","ändern":"LOGIK","äußerlich":"KOERPER",
"öffnen":"WOHNEN","übernehmen":"ARBEIT","überprüfen":"ARBEIT","übertreiben":"GEFUEHLE",
}
